### ISSUE TITLE
How to make iife compiled Prosemirror

### ISSUE THREAD

**Issue by liyasthomas** [muthu32/tiptap-demo#1]
Hi @muthu32 
I've seen your Codepen demo of tip-tap editor. I would like to know how you compiled prosemirror for that demo..?

While tweaking on that demo, I found copy paste functionality is not working.

**Comment by muthu32** [comment]
HI @liyasthomas 
Updated the Readme text that mentions how to compile prosemirror iife. Edit index.js and package.json according to your needs.
